import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import AddForm from "@/components/AddForm";
import GetForm from "@/components/GetForm";
import { useState } from "react";
import { Button } from "antd";

export default function Home() {
  const [tab, setTab] = useState(0);
  const listComp = [<AddForm key={0} />, <GetForm key={1} />];
  let emptyArray = ["Add Words", "Get Translations"];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.mainnav}>
          {emptyArray.map((menu, index) => {
            return (
              <Button
                type={`${index === tab ? "primary" : "default"}`}
                key={index}
                onClick={() => setTab(index)}
              >
                {menu}
              </Button>
            );
          })}
        </div>
        {listComp.map((component, index) => {
          return (
            <div
              key={index}
              className={`${styles.menu} ${index === tab ? styles.active : ""}`}
            >
              {component}
            </div>
          );
        })}
      </main>
    </>
  );
}
